---
slam_toolbox:
  ros__parameters:
    use_sim_time: True
    slam_algorithm: sync
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    resolution: 0.05
    max_laser_range: 8.0
    minimum_time_interval: 0.5
    transform_publish_period: 0.02
    map_update_interval: 1.0
